### ISSUE TITLE
[Bug]  Application stuck in "Offline Mode" !

### ISSUE THREAD

**Issue by GHAPITestCode** [DJDoubleD/refreezer#111]
# **🐞 Bug Report**

## **Describe the bug**
Les musiques ne sont plus accessibles. Le bouton "Mode hors connexion" s'est mis sur "ON" tout seul et on ne peut plus le passer à "OFF" !!

---

### **Screenshots**

![Image](https://github.com/user-attachments/assets/b306cfa5-3337-4811-8409-0c763d55e769)

![Image](https://github.com/user-attachments/assets/8f651768-320a-43f5-b114-1b53a1b21aaf)

---

### **Additional context**

*

**Comment by DJDoubleD** [comment]
1. Please use English, there are plenty if good translation tools out there if you need them.

2. First make sure your device has a good internet connection before you open the app and try to toggle the offline setting off.

3. If this doesn't work, close the app, delete the app storage in the android app settings, relaunch the app and log in again with a valid account.

**Comment by GHAPITestCode** [comment]
Sorry, I just changed the title to English.
Even with a good internet connection, you can no longer turn off the offline setting.
I closed the app, cleared the app cache in the Android app settings, and uninstalled the app.
After reinstalling, everything works again ! Thanks @DJDoubleD ...
It's really weird that the "Offline Mode" button toggles on its own, right?

If we clear the "data" part of the application in the Android application settings, does it only delete the ReFreezer settings?

**Comment by DJDoubleD** [comment]
> It's really weird that the "Offline Mode" button toggles on its own, right?

The offline mode never "just" toggles on it's own. If it got toggled, it means there was at least at one point an app launch where the app couldn't connect to deezer. Usually this is due to no internet connection during start, but it might just as well have been a problem specifically connecting to Deezer.
Once connection is restored, the user should be able to untoggle offline mode, but in your case, clearly something went wrong.

> If we clear the "data" part of the application in the Android application settings, does it only delete the ReFreezer settings?

It should delete everything, including ReFreezers internal dabatase and saved credentials (cookies).
I've yet to discover what goes wrong when the app refuses playback.
It's very hard to debug long sessions, unfortunately :(

**Comment by GHAPITestCode** [comment]
OK ! I understand.

I have another phone on which the previous manipulation does not work ...
I closed the app, cleared the "Cache" and "Data" in Android settings, and uninstalled the app.
After reinstalling, it's still the same: the "Offline Mode" button is still active even with a good connection.
However, on this phone, even after clearing the "Cache" and "Data," it automatically reconnects to the account without entering the email and password!!

Can you tell me if it's possible to manually remove the ReFreezer installation?

**Comment by DJDoubleD** [comment]
> OK ! I understand.
> 
> I have another phone on which the previous manipulation does not work ... I closed the app, cleared the "Cache" and "Data" in Android settings, and uninstalled the app. After reinstalling, it's still the same: the "Offline Mode" button is still active even with a good connection. However, on this phone, even after clearing the "Cache" and "Data," it automatically reconnects to the account without entering the email and password!!
> 
> Can you tell me if it's possible to manually remove the ReFreezer installation?

I'm not sure how to prevent Android from retaining app data on uninstall.
Perhaps doing a "force close" from the app settings screen, before clearing cache and data, might allow Android to do a reall full uninstall?

It might depend on Android version.
I fear you would need to google your phone model and android version with the question of why appdata doesn't get removed upon app uninstall...

**Comment by GHAPITestCode** [comment]
Ok. I'll take a look.

**Comment by Heisenberg-tr** [comment]
I fixed bug by clearing data then logging in

**Comment by GHAPITestCode** [comment]
Yes, I did that too (clearing only the cache is not enough).

**Comment by sevanmeister** [comment]
I have the same issue where it's sucking offline mode this occurred after the Google security update last night. I tried clearing the cache I deleted all the data I uninstalled the app reinstall the new app and I'm still getting the same offline mode it will not turn off.

**Comment by sevanmeister** [comment]
Following Google Android's new security updates last night, your app is stuck an offline mode you cannot toggle it off. I attached an image.

![Image](https://github.com/user-attachments/assets/066aab8f-a912-456b-9d4d-79e76e2d5bff)

**Comment by Heisenberg-tr** [comment]
Can anybody that suffering from the bug send logs?

**Comment by revilcpu** [comment]
G le même problème. la désinstallation/réinstallation ne résoud rien.
comment envoyer les journaux ?

**Comment by Heisenberg-tr** [comment]
Translation "I have the same problem. Uninstalling/reinstalling doesn't solve anything.
How do I send the logs?"

To send logs you need a logcat reader app (i use logcat reader professional) then click filter by apps after that select refreezer then logs will appear.

**Comment by peteh** [comment]
Can confirm this issue on my nothing phone 2a

Why can the log data not be copied? 

![Image](https://github.com/user-attachments/assets/aab0fd9a-f79e-496c-8fbc-8644ed4f7fe2)

**Comment by Heisenberg-tr** [comment]
Source error hmm interesting...

**Comment by peteh** [comment]
Let me know if you need more and how to get it

**Comment by DJDoubleD** [comment]
Ok, I finally managed to reproduce this issue while debugging.
The problem is that the logged in session (most likely when logged in with an ARL token) gets invalidated by the Deezer servers, causing the login to fail when the app is opened, locking it in offline mode.

When this happens, the user needs to Log out of the app and log in again with email/password (through app or Browser) or a new valid ARL token. 

I'm gonna leave the issue open for now until I can implement a clearer message for the user why the offline mode cannot be disabled.

**Comment by peteh** [comment]
> Ok, I finally managed to reproduce this issue while debugging. The problem is that the logged in session (most likely when logged in with an ARL token) gets invalidated by the Deezer servers, causing the login to fail when the app is opened, locking it in offline mode.
> 
> When this happens, the user needs to Log out of the app and log in again with email/password (through app or Browser) or a new valid ARL token.
> 
> I'm gonna leave the issue open for now until I can implement a clearer message for the user why the offline mode cannot be disabled.

I can confirm, logging out and in again (I used email login) solves the issue.

**Comment by Heisenberg-tr** [comment]
I can confirm too
